name: CI
on: push
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }} # e.g. v1.0.0
      version: ${{ steps.release-please.outputs.version }} # e.g. 1.0.0
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-github-token
        with:
          app_id: ${{ vars.RELEASE_PLEASE_GITHUB_APP_ID }}
          private_key: ${{ secrets.RELEASE_PLEASE_GITHUB_APP_PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          token: ${{ steps.generate-github-token.outputs.token }}
          command: manifest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install

      - name: Run linter
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - rails6
          - rails7
        ruby_version:
          - 2.7
          - "3.0"
          - 3.1
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

  release:
    runs-on: ubuntu-latest
    needs: [release-please, test]
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Export version from tag name
        run: echo ${GITHUB_REF/refs\/tags\//} > VERSION

      - name: Build Gem
        run: gem build *.gemspec

      - name: Setup credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{secrets.KRYSTAL_RUBYGEMS_API_KEY}}

      - name: Publish to RubyGems
        run: |
          gem push *.gem
